### ISSUE TITLE
[jsapi4] ie11 pan stutter

### ISSUE THREAD

**Issue by terenceng2010** [terenceng2010/jsapi-workaround#30]
ie11 in windows 8 and upper, pan does not work properly due to additional touch events. (work in win 7 ie11)

workaround: disable touch-events emission for ie11:

js:
```javascript
        var isIE11 = !!window.MSInputMethodContext && !!document.documentMode;
        if(isIE11){
            delete window.PointerEvent;
            window.navigator.msPointerEnabled = false;
        }
```
css:
```css
.map{
    -ms-touch-action: none;
    -ms-touch-select: none;
    -ms-user-select: none;
}
```

ref:
https://stackoverflow.com/questions/29752190/ol3-with-ie11-in-a-c-sharp-webbrowser-control-mouse-click-events-not-working
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/dn394063(v=vs.85)
